import 'package:http/http.dart' as http;
import 'dart:convert';
import '../models/clock_event.dart';
import '../models/shift.dart';
import '../models/exception_record.dart';
import '../models/leave_request.dart';
class ExceptionEngine {
  static const String _backendUrl = 'http://localhost:8000';

  /// Process a new clock event (in or out) to see if it generates an exception
  static Future<ExceptionRecord?> processClockEvent({
    required ClockEvent event, 
    required Shift? scheduledShift, 
    required int allowedLateMinutes, 
    required int allowedOvertimeMinutes,
    required String organizationId,
  }) async {
    
    // 0. Push event to the Python AI/ML backend for anomaly detection
    try {
      await http.post(
        Uri.parse('$_backendUrl/ingest'),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          'id': event.id,
          'employee_id': event.employeeId,
          'organization_id': organizationId,
          'event_type': event.eventType,
          'event_time': event.eventTime.toIso8601String(),
        }),
      );
    } catch (e) {
      print('Warning: Failed to reach AI backend: $e');
    }
    // 1. Roster Breach: Clocking in without a scheduled shift
    if (event.eventType == 'clock_in' && scheduledShift == null) {
      return ExceptionRecord(
        id: '', // ID will be auto-generated by Supabase
        organizationId: organizationId,
        employeeId: event.employeeId,
        exceptionType: 'roster_breach',
        severity: 'high',
        status: 'pending',
        description: 'Employee clocked in without a scheduled shift.',
        createdAt: DateTime.now(),
      );
    }

    if (scheduledShift != null) {
      // 2. Excessive Overtime: Clocking out significantly past shift end
      if (event.eventType == 'clock_out') {
        final overtimeDuration = event.eventTime.difference(scheduledShift.endTime);
        if (overtimeDuration.inMinutes > allowedOvertimeMinutes) {
          return ExceptionRecord(
            id: '', 
            organizationId: organizationId,
            employeeId: event.employeeId,
            exceptionType: 'excessive_overtime',
            severity: 'medium',
            shiftId: scheduledShift.id,
            status: 'pending',
            description: 'Employee clocked out ${overtimeDuration.inMinutes} minutes after shift ended.',
            createdAt: DateTime.now(),
          );
        }

        // 3. Fair Work Act Compliance: Minimum 30min break for shifts > 5 hours.
        // In a full implementation, we would query the `breaks` table to see if a break was taken.
        // For the prototype rule engine, we flag shifts > 5 hours missing a break log.
        final shiftDuration = scheduledShift.endTime.difference(scheduledShift.startTime);
        if (shiftDuration.inHours >= 5) {
          // Check if break was recorded (simulate failure for demo if we haven't implemented breaks yet)
          final hasValidBreak = false; // Simulated: no break logged
          if (!hasValidBreak) {
             return ExceptionRecord(
              id: '', 
              organizationId: organizationId,
              employeeId: event.employeeId,
              exceptionType: 'fair_work_compliance_breach',
              severity: 'high',
              shiftId: scheduledShift.id,
              status: 'pending',
              description: 'Fair Work Act Breach: Shift exceeded 5 hours without a logged 30-minute break.',
              createdAt: DateTime.now(),
            );
          }
        }
      }
    }

    return null; // No exception detected
  }

  /// Evaluates shifts to find missed clock-ins.
  /// Typically run periodically by a background task or when a manager opens the dashboard.
  static List<ExceptionRecord> detectMissedClockIns({
    required List<Shift> activeShifts, 
    required List<ClockEvent> todayEvents, 
    required int allowedLateMinutes,
    required String organizationId,
  }) {
    List<ExceptionRecord> exceptions = [];
    final now = DateTime.now();

    for (var shift in activeShifts) {
      final timeSinceStart = now.difference(shift.startTime);
      
      // If the shift started more than [allowedLateMinutes] ago
      if (timeSinceStart.inMinutes > allowedLateMinutes) {
        
        // Check if there is a 'clock_in' event for this employee matching this shift timeframe
        final hasClockedIn = todayEvents.any((event) => 
          event.employeeId == shift.employeeId && 
          event.eventType == 'clock_in' &&
          event.eventTime.isAfter(shift.startTime.subtract(const Duration(hours: 2))) &&
          event.eventTime.isBefore(shift.endTime)
        );

        if (!hasClockedIn) {
          exceptions.add(ExceptionRecord(
            id: '',
            organizationId: organizationId,
            employeeId: shift.employeeId,
            exceptionType: 'missed_clock_in',
            severity: 'high',
            shiftId: shift.id,
            status: 'pending',
            description: 'Employee missed clock-in by more than $allowedLateMinutes minutes.',
            createdAt: DateTime.now(),
          ));
        }
      }
    }

    return exceptions;
  }

  /// Evaluates rostered shifts against approved leave requests to detect conflicts.
  static List<ExceptionRecord> detectLeaveConflicts({
    required List<Shift> upcomingShifts,
    required List<LeaveRequest> approvedLeave,
    required String organizationId,
  }) {
    List<ExceptionRecord> exceptions = [];

    for (var shift in upcomingShifts) {
      // Find if this shift overlaps with any approved leave for the same employee
      for (var leave in approvedLeave) {
        if (shift.employeeId == leave.employeeId && leave.status == 'approved') {
          // Check for overlap: shift starts before leave ends AND shift ends after leave starts
          // (Assuming start/end dates for leave are inclusive of the whole day, or precise times)
          if (shift.startTime.isBefore(leave.endDate) && shift.endTime.isAfter(leave.startDate)) {
            exceptions.add(ExceptionRecord(
              id: '',
              organizationId: organizationId,
              employeeId: shift.employeeId,
              exceptionType: 'leave_roster_conflict',
              severity: 'high',
              shiftId: shift.id,
              status: 'pending',
              description: 'Shift scheduled during approved ${leave.leaveType} leave.',
              createdAt: DateTime.now(),
            ));
            break; // Record one conflict per shift max
          }
        }
      }
    }

    return exceptions;
  }

  /// Evaluates shifts to ensure minimum rest periods between shifts (10 hours under Fair Work).
  static List<ExceptionRecord> detectRestBreaches({
    required List<Shift> upcomingShifts,
    required List<Shift> pastShifts,
    required String organizationId,
  }) {
    List<ExceptionRecord> exceptions = [];
    
    // Combine and sort shifts by start time
    final allShifts = [...pastShifts, ...upcomingShifts];
    allShifts.sort((a, b) => a.startTime.compareTo(b.startTime));

    for (int i = 1; i < allShifts.length; i++) {
      final prevShift = allShifts[i - 1];
      final currShift = allShifts[i];

      // Only check if it's the same employee
      if (prevShift.employeeId == currShift.employeeId) {
        final restDuration = currShift.startTime.difference(prevShift.endTime);
        
        // Fair Work Act Minimum Rest is generally 10 hours
        if (restDuration.inHours < 10 && restDuration.inHours >= 0) {
           exceptions.add(ExceptionRecord(
             id: '',
             organizationId: organizationId,
             employeeId: currShift.employeeId,
             exceptionType: 'fair_work_compliance_breach',
             severity: 'high',
             shiftId: currShift.id,
             status: 'pending',
             description: 'Fair Work Act Breach: Minimum 10 hour rest period not met between shifts. Only ${restDuration.inHours} hours rest.',
             createdAt: DateTime.now(),
           ));
        }
      }
    }

    return exceptions;
  }
}
